# Errbit Config
# =============
#
# Copy this file to config/config.yml and
# modify it accordingly. This file will automatically
# be copied to shared/config on the server when
# `cap deploy:setup` is ran the first time. Be sure
# to place production specific settings there

# The host of your errbit server
host: errbit.example.com

# The email address which email notifications
# will be sent from.
email_from: errbit@example.com

# Configure when emails are sent for an error.
# [1,3,7] = 1st, 3rd, and 7th occurence triggers
# an email notification.
email_at_notices: [1, 10, 100]

# Set to false to suppress confirmation when 
# resolving errors.
confirm_resolve_err: true
