# Errbit Config
# =============
#
# Copy this file to config/config.yml and
# modify it accordingly. This file will automatically
# be copied to shared/config on the server when
# `cap deploy:setup` is ran the first time. Be sure
# to place production specific settings there
# You will need to restart the server after changing any settings.

# The host of your errbit server
host: errbit.example.com

# The email address which email notifications
# will be sent from.
email_from: errbit@example.com

# If you turn on this option, email_at_notices can be
# configured on a per app basis, at the App edit page
per_app_email_at_notices: false

# Configure when emails are sent for an error.
# [1,3,7] = 1st, 3rd, and 7th occurence triggers
# an email notification.
email_at_notices: [1, 10, 100]

# Configure whether or not the user should be prompted before resolving an error.
confirm_resolve_err: true

# Add an optional 'username' field to Users.
# Helpful when you need to plug in a custom authentication strategy, such as LDAP.
user_has_username: false

# Allow comments while an issue tracker is configured.
# This is useful if the err is not critical enough to create a ticket,
# but you want to leave a short comment.
allow_comments_with_issue_tracker: true

# Configure SMTP settings. If you are running Errbit on Heroku,
# sendgrid will be configured by default.
# ------------------------------------------------------------------------
#smtp_settings:
#  :address:              ADDRESS
#  :domain:               DOMAIN
#  :port:                 "25"
#  :authentication:       :plain, :login, :cram_md5
#  :enable_starttls_auto: true
#  :user_name:            USERNAME
#  :password:             PASSWORD

