[errbit]
host = "errbit.example.com"
user_has_username = false
mongo_url = "mongodb://localhost"
confirm_err_actions = true
confirm_resolve_err = true
per_app_notify_at_notices = false
per_app_email_at_notices = false
email_at_notices = [1, 10, 100]
notify_at_notices = [0]
devise_modules = ["database_authenticatable", "recoverable", "rememberable", "trackable", "validatable", "omniauthable"]
log_location = "STDOUT"
notice_deprecation_days = 7

[email]
from = "errbit@example.com"
delivery_method = "smtp"

[smtp.settings]
address = ""
port = 587
domain = ""
user_name = ""
password = ""
authentication = ""
enable_starttls = false
enable_starttls_auto = true
openssl_verify_mode = "peer"
tls = true
open_timeout = 30
read_timeout = 30

[sendmail.settings]
location = ""
arguments = ""

[gravatar]
enabled = false
default = "identicon"

[github]
enabled = false
url = "https://github.com"
api_url = "https://api.github.com"
site_title = "GitHub"
access_scope = ["repo"]
client_id = ""
secret = ""
org_ids = []

[google]
enabled = false
site_title = "Google"
redirect_uri = ""
client_id = ""
secret = ""
authorized_domains = []
auto_provision = false
