[main]
host = "errbit.example.com"
devise_modules = ["database_authenticatable", "recoverable", "rememberable", "trackable", "validatable", "omniauthable"]
user_has_username = false
mongo_url = "mongodb://localhost"
email_at_notices = [1, 10, 100]
per_app_notify_at_notices = false
notify_at_notices = [0]
per_app_email_at_notices = false
confirm_err_actions = true

[email]
from = "errbit@example.com"

[gravatar]
enabled = false
default = "identicon"

[github]
enabled = false
url = "https://github.com"
api_url = "https://api.github.com"
site_title = "GitHub"
access_scope = ["repo"]
client_id = ""
secret = ""

[google]
enabled = false
site_title = "Google"
redirect_uri = ""
client_id = ""
secret = ""
authorized_domains = []

#CONFIRM_RESOLVE_ERR=true
#ALLOW_COMMENTS_WITH_ISSUE_TRACKER=true
#SECRET_KEY_BASE=fsdfds
#ERRBIT_LOG_LOCATION=STDOUT
