# Mongoid Configuration for MongoHQ on Heroku
# ===========================================
#
# Copy this file to config/mongoid.yml,
# commit it to your repo, then push to heroku.

production:
  uri: <%= ENV['MONGOHQ_URL'] %>